### ISSUE TITLE
Set up testing for notebooks

### ISSUE THREAD

**Issue by mdpiper** [csdms/ivy#27]
All Jupyter Notebooks used in ESPIn should be tested, and the tests should be run under continuous integration.

**Comment by mdpiper** [comment]
There doesn't appear to be a clear method for doing this. One possibility: if we save each Notebook in an "already run" state, we could use nbval, which integrates with pytest, to run the Notebook and compare the result.

* nbval repo: https://github.com/computationalmodelling/nbval
* nbval docs: https://nbval.readthedocs.io/

**Comment by mdpiper** [comment]
@mcflugen has a workflow in https://github.com/csdms/pymt/pull/133 we can use.

**Comment by alex-treebeard** [comment]
hey there, I maintain a [pytest plugin](https://github.com/treebeardtech/nbmake) for this in case it helps, feedback very welcome.

**Comment by mdpiper** [comment]
See how @mcflugen uses `nbmake` in https://github.com/landlab/landlab/pull/1541.

**Comment by mdpiper** [comment]
Fixed with #90 (using `nbmake`!).
